"""
Problem 2: 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

num2 = 0
num3 = 1
fib = [1, 1]
even = 0
for _ in range(35):
    fib_previous = fib[-1]
    fib_previous_two = fib[-2]
    fib_total = fib_previous + fib_previous_two
    if fib_total > 4000000:
        break
    else:
        fib.append(fib_total)
        if fib_total % 2 == 0:
            even += fib_total
print(even)
